### ISSUE TITLE
gRPC/HTTP2 support

### ISSUE THREAD

**Issue by bbutcher** [Azure/application-gateway-kubernetes-ingress#1015]
When will AGIC support http2?  This is becoming more important as we deploy gRPC services to AKS.

I know I can workaround this with grpc.web but it is adding extra steps to our development.

**Comment by dhananjaya-senanayake** [comment]
Please provide an ETA on the gRPC support

**Comment by jruckert** [comment]
Any update on this @mscatyao?

**Comment by colin-barlow-swi** [comment]
HI @mscatyao is there an update of the gRPC ETA?

**Comment by fractiunate** [comment]
+1

**Comment by zalegrala** [comment]
If working with AKS, the nginx ingress can be modified to receive gRPC traffic in Azure.

**Comment by mirgil** [comment]
> We are planning to work on gRPC in CY22, we should have a better idea of approximate ETA around Feb 2022.

Any update on supporting gRPC?
Is there a change it will be in CY22?

**Comment by techgeek03** [comment]
Any updates on this @mscatyao ? We have been using gRPC for over two years now and been forced to use both AGW and Azure Firewall. HTTP3 is just around the corner and we still don't have HTTP2 in any of the current Azure products.

**Comment by periapsistech** [comment]
@jovicde any updates on supporting HTTP2 or gRPC in the AGIC?

**Comment by jovicde** [comment]
> @jovicde any updates on supporting HTTP2 or gRPC in the AGIC?

Not that I am aware of. We switched to SignalR due to lack of gRPC support in Azure. Also, SignalR supports true bi-di communication, while in gRPC we had to deal with infinite function calls to eventually fire server-sent events. Felt a bit like the forever frame in the good old days.

**Comment by xsoheilalizadeh** [comment]
We are adapting our services to use HTTP/2 it would be necessary for us to have this feature.

**Comment by bborovan** [comment]
Is there any update on gRPC support?

**Comment by e96wic** [comment]
Microsoft just told me
> This topic is still in the backlog of the team, and we do not have an ETA on it.

**Comment by bborovan** [comment]
Thanks for passing this on @e96wic and good to know, though seems to confirm this is not their priority and no point holding breath on it. No ETA = don't count on it any time soon, if i read between the lines.

**Comment by PeretzBatel** [comment]
Hello, is there yet support for HTTP2?

**Comment by omutas** [comment]
@mscatyao is this on your schedule for 2023?

**Comment by jcoxcomdata** [comment]
I'm using ApplicationGateway in front of my Kubernetes Cluster (AKS).
I've deployed a container that I want to support Bidirectional streaming.  

When running locally (in VisualStudio on laptop) the code does (and is expected to) "wait" here
await foreach (var y in z.ResponseStream.ReadAllAsync(ct))
{ code is supposed to wait here... } [all this works as expected on local laptop]

When the code is deployed behind the ApplicationGateway any attempts to access the ResponseStream doesn't appear to be an option.
System.InvalidOperationException: Can't write the message because the request is complete.

I get an IOException when using ApplicationGateway while attempting to try and support the Bidirectional streaming. Example: IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

This is an example proto file for context.
rpc SubscribeBiDirectionalStream (stream SubscriberResults) returns (stream SubscriberResult);

I suspect based on the comments above that the ApplicationGateway can't support bidirectional streaming.
I've tried gRPC, and gRPC-Web and can't get either to work behind the ApplicationGateway with bidirectional streaming.

Should I just drop the ApplicationGateway and switch to a direct NGINX ingress controller?
Any timelines, thoughts on how to go about supporting bidirectional streaming/websockets?

**Comment by xsoheilalizadeh** [comment]
We switched completely to https://github.com/traefik/traefik, @jcoxcomdata it might be an option for you.

**Comment by mdanylyuk** [comment]
Hello guys
Is there any news about supporting gRPC in AGIC?

**Comment by haorenfsa** [comment]
@akshaysngupta Any comment about this feature? Is there still any plan? It's quite critical if we want to use AGIC.

**Comment by dfenerski** [comment]
We are experiencing faulty behavior because `HTTP2` is `enabled` on Azure Application Gateway and I now find out agic does not support this. Weird functionality mismatch IMO

**Comment by N8-I** [comment]
![its-been84years-titanic](https://github.com/Azure/application-gateway-kubernetes-ingress/assets/91631390/470e8e74-0156-444b-9e85-3db247d1062f)

**Comment by shubhamdeodia** [comment]
We need this :-(

**Comment by fforootd** [comment]
Its good to see that I am not the only one who finds this weird 🤣

**Comment by fractiunate** [comment]
MS seems to not care about feature that does not bring revenue...  (or promotes competitors products like grpc) :(

**Comment by N8-I** [comment]
Is using the Azure Load Balancer with a different ingress controller a viable alternative?

**Comment by djfr** [comment]
You can mix and match ingress controllers. We use both the appgateway and the nginx ingress controllers, nginx will use the load balancer deployed for the nodepool.

Another annoying quirk of the appgateway is that if you have frontdoor/cloudflare at the top of the ingress, the appgateway will rewrite X-Forward headers from frontdoor/cloudflare, you need to put in a special policy to re-write them again to what frontdoor outputs.

**Comment by mdanylyuk** [comment]
If we use the default Nginx ingress controller to publish services what's the reason for mixing it with AGW - you can publish APIs/gRPCs/frontend/etc. So what's the reason to use AGW at all? (the logical question isn't it?)

But for me, it's rather a question of not using lots of solutions and not creating chaos in the system) (except of using benefits of AGW by default)

**Comment by mdanylyuk** [comment]
Hello
Guys, is there any news about supporting gRPC?

**Comment by nvenkatapavan** [comment]
Hi everyone, 
Any update on gRPC or any alternative solution?

**Comment by qwertoyo** [comment]
greetings from 2024, where gRPC is finally taking the place of that global hallucination that was REST and the ambiguity of data shared with json, for service-to-service calls at least

it would be very nice if such a feature was supported on Azure App Gateway! We can do it on e.g. AKS, why not here? 🙏

**Comment by haorenfsa** [comment]
> Hi everyone, Any update on gRPC or any alternative solution?

@nvenkatapavan We uses nginx ingress togther with azure's Layer 4 LB.
check the `Configure ingress nginx` Section in  https://milvus.io/docs/ingress.md . It works for any gRPC service.

**Comment by baswelsh** [comment]
+1

**Comment by mdanylyuk** [comment]
Hi everyone,
Any updates on this issue?

**Comment by JackStromberg** [comment]
We are excited to announce gRPC has been released in Application Gateway for Containers.  We do not have plans on porting this feature to AGIC.

More information can be found here: https://learn.microsoft.com/azure/application-gateway/for-containers/grpc

**Comment by vikas-gautam** [comment]
Application Gateway for Containers is just another service for revenue/profit.

You’re blocked from using gRPC with existing infra
If you're using AGIC with the traditional App Gateway, you cannot expose gRPC services due to lack of http2/grpc support.

You’d need to re-architect or migrate to the newer Application Gateway for Containers (AGWC), which may not yet be GA in your region or supported by your IaC tools (terraform & others)



> er 4 L
we are also doing the same but this brings a separate traffic flow for exposed gRPC services instead of what non-gRPC applications are following i.e. AGIC with traditional app gateway.

split the traffic flow:

gRPC services: Internet → NGINX Ingress with load balancer type service i.e. NLB → gRPC pods

Non-gRPC services: Internet → App Gateway (AGIC) → app pods

**Comment by vikas-gautam** [comment]
> > Hi everyone, Any update on gRPC or any alternative solution?
> 
> [@nvenkatapavan](https://github.com/nvenkatapavan) We're using nginx ingress together with azure's Layer 4 LB. check https://kubernetes.github.io/ingress-nginx/examples/grpc/. It works for any gRPC service.


we are also doing the same but this brings a separate traffic flow for exposed gRPC services instead of what non-gRPC applications are following i.e. AGIC with traditional app gateway.
spliting the traffic flow:
gRPC services: Internet → NGINX Ingress with load balancer type service i.e. NLB → gRPC pods
Non-gRPC services: Internet → App Gateway (AGIC) → app pods

**Comment by JackStromberg** [comment]
@cluster2a @vikas-gautam happy to sync with you to understand any concerns on Application Gateway for Containers addressing the gRPC need. Please reach out at firstname.lastname at the company I work for via email.

For others finding this thread, the recommendation for gRPC is to transition from AGIC to Application Gateway for Containers: https://learn.microsoft.com/azure/application-gateway/for-containers/grpc
