### ISSUE TITLE
AppGateway returns 502 on 204 response

### ISSUE THREAD

**Issue by StephanNel** [Azure/application-gateway-kubernetes-ingress#1108]
**Describe the bug**
Application hosted in K8s returns a 204 code on requests that return no data. The 204 is not returned to the Front-end  when routing through Application Gateway instead the 204 is returned as 502 - Bad Gateway

When running the site bypassing the ingress the correct response is returned to the Front-End

* Any Azure support tickets associated with this issue.
 120111221001214

**Comment by gpowers01** [comment]
> **Describe the bug** Application hosted in K8s returns a 204 code on requests that return no data. The 204 is not returned to the Front-end when routing through Application Gateway instead the 204 is returned as 502 - Bad Gateway
> 
> When running the site bypassing the ingress the correct response is returned to the Front-End
> 
> * Any Azure support tickets associated with this issue.
>   120111221001214

@StephanNel  - did you ever determine the root cause and steps to resolve this issue?  We are experiencing a similar issue with an intermittent 502 Bad Gateway error, but no indications of why or exactly where between the App Gateway -> APIC -> backend API server the unhealthy condition is coming from to cause the 502.

**Comment by facundogc** [comment]
Did you ever find a solution for this? I'm getting the same. As far as I understand this may be happening because a 204 expects there to be no body, so if there is one it fails. However, my request returns 204 and no body, I see it when debugging, yet it somehow still turns into a 502. If I change it to return 200 it works with no issue, but that's not what I'm looking for
