### ISSUE TITLE
Question: Upgrading AGIC without Helm?

### ISSUE THREAD

**Issue by RagingRudolf** [Azure/application-gateway-kubernetes-ingress#1173]
I have just started working with Kubernetes and I managed to install Application Gateway Ingress. I found out that some annotations are not working and that could be cause by using a too old version of AGIC. Right now I'm using version 1.2.1 according to my workload pod for application gateway.

How do I upgrade the version? I activated the ingress controller through the Azure Portal and not through Helm charts ( to be honest I have no knowlegde about it yet).

I tried to go to the pods YAML and tried to bump the version to 1.4.0 but that does not seem to work as it has been rolled back during night.

Anyone who can give me some advice?

**Comment by akshaysngupta** [comment]
AGIC 1.4.0 rollout should start this coming week and reach all regions in a week or so.

**Comment by fatpowaranga** [comment]
@RagingRudolf Just for future reference in case it's not clear, as an Azure customer using Application Gateway Ingress Controller on an Azure Kubernetes Services cluster, you should not be managing the AGIC in the cluster. You may need to update the version of k8s for your AKS if it is especially old, if AGIC requires a later version of k8s.

**Comment by MayurDhande-GSLab** [comment]
@RagingRudolf Can you try if this works ?
```
kubectl -n kube-system set image deployment/ingress-appgw-deployment ingress-appgw-container=mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:<tag>

**Comment by nomaster** [comment]
I have just tried this and it doesn't work.

After manually editing the deployment resource, some automation supersedes the operation and puts the old version back in place:

> Operation PutApplicationGatewayOperation (03d0a58b-50c0-4569-9afc-7c99a4f766b9) was canceled and superseded by operation PutApplicationGatewayOperation (4fc4316b-d5c5-463b-9e11-5938d1bac618).

I have version 1.5.3 running and would like to receive an update.

**Comment by kchervonets** [comment]
@nomaster Did you find a way to upgrade? I;m facing the same problem.

**Comment by nomaster** [comment]
I just looked again into the issue and found that you can perform an upgrade with the following Azure CLI command:

```
az aks addon update \
--addon ingress-appgw \
--resource-group $resource_group \
--name $cluster_name \
--appgw-id /subscriptions/$subscription_id/resourceGroups/$resource_group/providers/Microsoft.Network/applicationGateways/$application_gateway_name
```

**Comment by nomaster** [comment]
@kchervonets thanks for reminding me 😄

**Comment by kethahel99** [comment]
Hey friends!

Thank you for the great suggestions. 

 I tried the following and unfortunately it did not work:

1. Update the image version in the deployment. This reverts back to 1.5.3 (what was installed at the time the add on was installed) because the cluster manages the add-on lifecycle. No dice... 😔
2. Tried to upgrade using the aks addon update script. This also did not work and the version stayed on 1.5.3. No cigar...again 👎🏻 😔


I did dome more digging and found that the reason why is because my AKS cluster version for control plance and node pools needed an updrade.

This article also explains very well that "The major/minor version of the add-on is only upgraded when moving to a later Kubernetes minor version."
https://learn.microsoft.com/en-us/azure/aks/integrations#add-ons

I upgraded my AKS cluster to the latest recommended patch channel and it updated all my add-ons correctly. 🚀🚀🚀

Hope this helps!
