### ISSUE TITLE
When is AGIC Add-on updated to 1.6.0 

### ISSUE THREAD

**Issue by jhoeflaken** [Azure/application-gateway-kubernetes-ingress#1513]
I have installed AGIC as add-on in my AKS cluster but AGIC is still 1.5.2 while 1.6.0 has some features I really need. When will this be updated or is there a way to do it yourself?

**Comment by antymon4o** [comment]
@akshaysngupta, Do you know is there a plan versions 1.6 and 1.7 of AGIC to be made available to use in AKS through the add-on? 
This is very important for us, because we want to use AzureApplicationGatewayRewrite which is available since 1.6.
And we have to make the choice - do we wait for the version 1.6 to be available through the add-on, or migrating to the helm deployment model?

**Comment by kugelblitzz** [comment]
I contacted Azure support, but they have no clue 🙄 regarding addon release dates

**Comment by obesser** [comment]
+1 because of this bug: https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1401
It reconfigures the listener to http instead of https, so in practice breaks access to the application.

**Comment by akshaysngupta** [comment]
AGIC 1.7.2 is available in AKS >= 1.27. Older AKS version will continue to get fixes.
