### ISSUE TITLE
Wildcard in base path not working without trailing slash

### ISSUE THREAD

**Issue by abenck** [Azure/application-gateway-kubernetes-ingress#458]
**Describe the bug**
Configuring a path with /sample/* changed in behavior:
example.com/sample/  <- works
example.com/sample  <- Doesn't work

The past few months everything worked fine without the trailing slash and we configured all our redirects to omit the trailing slash. We've been adding applications in production over the past few months and never experienced this problem before. The Azure ingress controller logs are fine and it's updating correctly. 

**To Reproduce**
Configure a host based ingress resource with wildcard paths
/example1/*
/example2/*

**Ingress Controller details**
NAME                  	REVISION	UPDATED                 	STATUS  	CHART              	APP VERSION	NAMESPACE
external-azure-ingress	1       	Mon May 20 14:05:31 2019	DEPLOYED	ingress-azure-0.4.0	0.4.0      	default  
internal-azure-ingress	1       	Mon May 20 14:06:02 2019	DEPLOYED	ingress-azure-0.4.0	0.4.0      	default

**Comment by akshaysngupta** [comment]
Investigating.

**Comment by ddevaal** [comment]
We have this exact same problem but with version 0.7.1.

**Comment by abenck** [comment]
This sounds like it could be the Application Gateway, was there a recent update for that?

**Comment by ddevaal** [comment]
@akshaysngupta Any updates on this issue?

**Comment by akshaysngupta** [comment]
@ddevaal @abenck Yes, this is a behavior change on Application Gateway. Customer notifications have been sent for this. The current/old behavior for a domain name without trailing / (for example contoso.com) was to send a redirect to one with trailing dash (for example contoso.com/). This is being changed to not sending a redirect. You will have to modify your path rules so that path rule without trailing / is handled explicitly as a new addition.

**Comment by lonevvolf** [comment]
This has effectively cut the number of allowed rules in half.  Please raise the limit.
