### ISSUE TITLE
Installation from stable Helm chart repository

### ISSUE THREAD

**Issue by littlenetcoder** [Azure/application-gateway-kubernetes-ingress#469]
Hi Team,

Any feature plan to support installation from stable helm chart repository?

Thanks

**Comment by akshaysngupta** [comment]
@littlenetcoder Do you mean that we place out charts in https://github.com/helm/charts/tree/master/stable ?

**Comment by littlenetcoder** [comment]
Yes @akshaysngupta

**Comment by delqn** [comment]
Hi @littlenetcoder,

This is a great idea - we looked into it.  A dependency of ours is AAD Pod Identity. The PR to add that to the stable Helm repo is here: https://github.com/helm/charts/pull/15306
It turns out it is not trivial to do that. The chart for that Helm package was created here: https://github.com/Azure/aad-pod-identity/pull/373 -- not in Helm Stable though.
So with that - I am going to close this issue. We'll keep the Helm chart in this repo here near term.
