### ISSUE TITLE
More than one ingress controller for namespace

### ISSUE THREAD

**Issue by Yiyito11** [Azure/application-gateway-kubernetes-ingress#504]
I know that application-gateway-kubernetes-ingress is now enabled for multiple namspaces. Thing is that apart from this ingress controller , we  also have an applicacion gateway that points to the AKS cluster, and some times new deployments are not showing up after they are created or they have some delay in refreshing. We have ### **namespace** dev, qa and stg. SO I think traffic through 1 app gateway > ingress controller (wathing 3 namespaces) > deployments with a lot of pods  in different namespaces is causing this , some times, slowness on get new deployments. 
What I want to know if  adding 3 ingress controllers with 3 App gateway pointing to the AKS cluster one per each namespace could be a good solution for less less traffic to the AKS cluster avoiding this refreshment delay. Also  I guess that I would need three new Managed Identity Controller (MIC) deployments, but should I also would be needing 3 Azure identities like explained here [https://github.com/Azure/aad-pod-identity](url) or with the one identity I alredy have for the App gateway and ingress controller already running would be enough?. 
What are your opinions of this.

Thanks!

**Comment by delqn** [comment]
@Yiyito11 Which version of the Ingress Controller are you using for the multiple namespaces?

With the latest version [0.9.0-rc2](https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/0.9.0-rc2) (released just today) we solved quite a few performance issues. You should be able to use a single App Gateway and a single Ingress Controller for your entire AKS cluster.

Would you be so kind to upgrade to 0.9.0-rc2 and report back? It'd be great to find out that the performance optimizations in the latest release fix the issues you ran into.

To answer your question - you could have one ingress controller per names space.  You could attach each ingress controller to a separate App Gateway, or you could even have them share a single App Gateway.  If you decide to go down the path of multiple ingress controllers sharing a single App Gateway, you are going to have to ensure they don't step on each other. Each Ingress Controller by default assumes full ownership of the App Gateway it is pointed to.  So multiple ingress controllers would be overwriting the App Gateway config they send. We recently added a feature called [Multi-cluster / Shared App Gateway](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-existing.md#multi-cluster--shared-app-gateway) - this allows you to set boundaries so that multiple ingress controllers can control a single app gateway.  Take a look at that document.  This does add complexity.

Please update this ticket when you get a chance to try v 0.9.0-rc2.  Documentation on how to upgrade using `help` is here:  https://github.com/Azure/application-gateway-kubernetes-ingress/blob/e28a1388ddc0cc0fa8efbedc595ae43ac7c91be2/docs/how-tos/helm-upgrade.md

**Comment by draychev** [comment]
Hi @Yiyito11,  we [released v1.0](https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/1.0.0) of the ingress controller.
Have you had a chance to install that latest stable version?
Would love to know whether all the improvements we shipped since you last upgraded address the issues you ran into.

**Comment by Yiyito11** [comment]
Hey Delyan! Yes! We update k8s every time we see there is a new Ingres controller release. All looks good now since you guys help us on the bug fix.
