### ISSUE TITLE
LetsEncrypt not working in 0.9

### ISSUE THREAD

**Issue by tesharp** [Azure/application-gateway-kubernetes-ingress#571]
**Describe the bug**
Aftre upgrading to 0.9 it is not able to update the AppGw correctly when redirect is enabled. Tested with downgrading to 0.8 and it works. In 0.9 it gets an error:

`cannot specify DefaultBackendAddressPool when RedirectConfiguration is specified`

**To Reproduce**
Create an ingress with annotations

```
appgw.ingress.kubernetes.io/ssl-redirect: "true"
certmanager.k8s.io/cluster-issuer: letsencrypt
``` 
Use a hostname not used before (so no certificate exists). When cert-manager tried to create the acme ingress it fails to update AppGw with url path rules to redirect acme response to that pod. Never get a certificate.

**Ingress Controller details**
* Output of `kubectl logs <ingress controller>. 

```
<entire appgw template>
... `cannot specify DefaultBackendAddressPool when RedirectConfiguration is specified`
```

urlPathMaps has defined `defaultBackendAddressPool`

**Comment by looping-18** [comment]
Same issue here : 

> E0930 16:43:23.185524       1 worker.go:49] Processing event failed:network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayRedirectConfigurationUrlPathMapCannotSpecify" Message="UrlPathMap /subscriptions/<subscription_id>/resourceGroups/<rg_name>/providers/Microsoft.Network/applicationGateways/<application_gateway_name>/urlPathMaps/url-<hostname>80 cannot specify DefaultBackendAddressPool when RedirectConfiguration is specified." Details=[]

**Comment by draychev** [comment]
@tesharp, @looping-18 thank you for reporting this issue and thanks for your patience.
As you can see from the open PRs against this issue - we found the root of the bug, and are also adding tests to cover this particular scenario.

The bug is caused by the automatic creation of a second Ingress resource by cert manager for the ACME protocol.

We will make another release of the Ingress Controller and update this issue.
