### ISSUE TITLE
Ingress Controller enforces a public frontend IP

### ISSUE THREAD

**Issue by ferhaty** [Azure/application-gateway-kubernetes-ingress#717]
Hi,

I'm getting the following error when deploying the AGIC with an existing Application Gateway. 

```
F0123 12:16:24.827632       1 main.go:122] Got a fatal validation error on existing Application Gateway config. Please update Application Gateway or the controller's helm config. Error:A Public IP must be present in the Application Gateway FrontendIPConfiguration
```

My Application Gateway does not have a public ip. It's internal only. Why is the public frontend IP enforced in the validator?

See also:
https://docs.microsoft.com/en-us/azure/application-gateway/configuration-overview#front-end-ip

**Comment by mscatyao** [comment]
Hey @ferhaty, it looks like you're using an AppGW v1 SKU. AGIC past the [0.9.0 release](https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/0.9.0) doesn't support AppGW v1 SKU. Given your error, we'll need to move the SKU validation before the public IP validation (since AppGW v2 currently must have at least a public IP).

**Comment by ferhaty** [comment]
@mscatyao Thanks! We tried AppGW v2 and it enforced a public IP. We need private IP only mode for our AGs or public IP mode with the ability to lock it down. So we went for the Nginx Ingress Controller for the time being until our enterprise org. supports AppGW v2.
