### ISSUE TITLE
Publish helm chart 1.1.0 to your repository

### ISSUE THREAD

**Issue by SychevIgor** [Azure/application-gateway-kubernetes-ingress#788]
**Describe the bug**
Theoretically, was released 1.1.0 version in February 2020. https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/1.1.0 , or at least somebody created a git tag 1.1.0, but didn't upload this 1.1.0 version to helm repo  https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/

The newest non-RC version according to this file is 1.0.0 https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/index.yaml
![image](https://user-images.githubusercontent.com/578954/78243174-f5e84d00-74eb-11ea-9b18-21e95a495872.png)

New chart version in Helm include fix for k8s 1.16.* where deployment api v1beta deprecated and should be used v1. 
Probably, also should be updated in values.yaml versions to 1.1.0 
![image](https://user-images.githubusercontent.com/578954/78250316-5b423b00-74f8-11ea-8a76-98682d3f8353.png)

@akshaysngupta Please, upload 1.1.0 version of charts to the repo to fix this bug.

**Comment by robinmanuelthiel** [comment]
#767

**Comment by SychevIgor** [comment]
@robinmanuelthiel agree, there are mane issues based on the same root problem- project released recently, but already not up-to-date to latest azure/kubernetes features.

**Comment by akshaysngupta** [comment]
Thanks for asking! We are going to make a release shortly.

**Comment by robinmanuelthiel** [comment]
Wait, what? According to this repository, [1.1.0](https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/1.1.0) is already released, @akshaysngupta. It just hasn't been added to the Helm repository feed. That's all we are asking for.

Nothing will break by just adding a new version to the Helm repo, as long as people don't deploy the new version to their clusters. But again, it is already released, just not via Helm.

**Comment by Baklap4** [comment]
Seems the release is deleted now...

**Comment by SychevIgor** [comment]
tag was deleted. Looks like tag 1.1.0 was created by mistake, because source code marked by this tag- was not reflect 1.1.0 versions for example. 

BTW- release of helm charts to address latest aks versions - is really important. Currently, looks like Microsoft don't invest enough to be as fast as AKS and K8s.

**Comment by akshaysngupta** [comment]
Hi all, yesterday, I created release [1.2.0-rc1](https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/1.2.0-rc1). This has the fix to `deployment` api-version which is needed for k8s version `1.16`. Because of the change in the api version, if you upgrade from an existing helm release, you will see a conflict when applying the deployment object. For now, you may have to create a new helm release to bypass the problem.

**Regarding tag 1.1.0**
Yes, Tag `1.1.0` is deleted now to avoid unnecessary confusion.
As fix to deployment api-version is a breaking change,`1.1.0` will not have it as it would not be appropriate to have a breaking change from an RC to non-RC.

**Relationship between Release Pipeline and Git Tags**
For the project, the way release pipeline is setup is, once a commit is tagged, it invokes the [public release pipeline](https://dev.azure.com/azure/application-gateway-kubernetes-ingress/_release?definitionId=1&view=mine&_a=releases). This pipeline has an approval gate and then three stages:
1. Create the docker image
1. Generate/upload the helm package
1. Create a Github release

So, until a release is green lighted in the approval step, the remaining stages are not triggered.

**Note on Ingress moving to `extensions/v1beta1`**
Also, important note is that k8s is moving from `extensions/v1beta1` to `networking/v1beta1` api version. Here is a PR addressing migrating the ingress: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/790. I will merge this after testing on both the ingress
