### ISSUE TITLE
Use the built-in Kubernetes Azure Cloud Provider for ARM authentication by default

### ISSUE THREAD

**Issue by robinmanuelthiel** [Azure/application-gateway-kubernetes-ingress#795]
When running a Kubernetes cluster in Azure, it should already have a Service Principal and an understanding of how to communicate and authenticate against ARM in its [Cloud Provider Config](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/docs/cloud-provider-config.md).

Currently, the two ways to authenticate AGIC against ARM are an addition Service Principal or AAD Pod Identity. While these are great options, I would like to suggest to use the built-in Service Principal of Kubernetes on Azure by default.

This would make the `armAuth.*` options optional and make the installation a lot easier and seamless.

The default installation process could be simplified and look like this:

1. Give the Service Principal the cluster already has `Reader` access to the App Gateway Resource Group and `Contributor` access to the App Gateway itself
1. Install AGIC with parameters `appgw.*` and `kubernetes.watchNamespace` only

*No more need to create a separate Service Principal or install AAD Pod Identity by default, if one does not want or need to use them.*

**Comment by akshaysngupta** [comment]
@robinmanuelthiel Thanks for asking. If you want to use AGIC with credentials from Cloud Provider Config, you can use it right now. All you need to do is omit `armAuth` section from the helm config.

**Beware: This is not recommended** for dev/production workload. Here are few reasons for that:
1. Cloud Provider Config contains the cluster service principal which has too much permission over the cluster resources. If not monitored, Cloud Provider Config can be mounted by any pod and would a cause of concern.
1. New AKS cluster will soon default to using [Managed Identity](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity). Clusters with MSI enabled will not have credentials in the Cloud Provider Config and would need all k8s deployments to manage their own identity using user assigned identity. Since AGIC installation steps use user assigned identity, steps would remain the same.

**Comment by robinmanuelthiel** [comment]
Thanks for clarifying. I didn't know, that I can use the Cloud Provider Config by just omitting the `armAuth` section. I couldn't find that information in the docs. 

Fair point, that AKS will move to MSI soon, but there might be non-AKS Kubernetes Cluster in Azure that still use the "old" setup, so please keep that as an option.

**Comment by akshaysngupta** [comment]
Closing this issue.
