### ISSUE TITLE
Deleting the cluster does not delete the backend pods on appGW

### ISSUE THREAD

**Issue by mhsh64** [Azure/application-gateway-kubernetes-ingress#911]
**Describe the bug**
When I have deleted the cluster which I had AGIC on it, the appGW still shows the backend pools which were running on the deleted cluster. Now AppGW shows those pools in unhealthy status
**To Reproduce**
Delete the AKS cluster which has the AGIC, but AppGW is not able to remove the pools were running on the deleted cluster

**Comment by akshaysngupta** [comment]
@mhsh64 This is as expected.
When a pod is getting deleted, it gets SIGTERM and SIGKILL signals from the OS. This could happen because there is rolling update on the POD or the node is being taken down or the AKS cluster is getting deleted. Since there is no way to distinguish these events, there is no special routine in AGIC to reset the App Gateway config. If we handle delete for AKS cluster by reseting the App gateway config, it would also affect the case where you are just trying to upgrade AGIC version. So, this is by design that we don't reset the App Gateway config.

**Comment by mhsh64** [comment]
Thanks.
@akshaysngupta Have a question.
Is this possible to configure one AppGW for multiple AKS clusters? Which the pods running onthose clusters share one identical domain name.
I mean we want to have an AppGW in front of multiple Clusters (which running AGIC on each of them ). Imaging having multiple clusters for dev, multiple clusters for qa . Now we want to have one AppGW for dev and one for qa
