### ISSUE TITLE
The ARM template is outdated for NodePools and Egress traffic through App gateway

### ISSUE THREAD

**Issue by vakkur** [Azure/application-gateway-kubernetes-ingress#916]
Is there an updated ARM template that uses VMSS for nodePool creations, add them to app gateway backend pool and I would like to know how we can egress the traffic through APP Gateway as it would be the only public IP for the cluster and I still get a random IP address when I try to access a web page from a pod.

https://raw.githubusercontent.com/Azure/application-gateway-kubernetes-ingress/master/deploy/azuredeploy.json

**Comment by akshaysngupta** [comment]
@vakkur I think updating the ARM template to at least deploy the AKS with VMSS node pool has been in our list for sometime now. But I think this template stills need some fixing to correctly deploy VMSS.
https://github.com/Azure/application-gateway-kubernetes-ingress/pull/751

Please feel free to contribute.

**Comment by akshaysngupta** [comment]
as a workaround, you can give AZ cli a try to deploy a cluster with your custom configuration.

**Comment by vakkur** [comment]
@akshaysngupta thank you for your response, I was able to deploy using the VMSS, I made changes to the existing template. 
But I would like to know how we can egress the traffic through APP Gateway as it would be the only public IP for the cluster and I still get a random IP address when I try to access the internet from a pod.

**Comment by deeksha-microsoft** [comment]
Hi @vakkur , egress from appgw is not possible as AppGw is a load balancer for the backend (a reverse proxy).
You could try and attach a public IP to your VMSS VMs individually, so that any traffic going out of a VM will have a fix PublicIP address. Below doc can guide you-
https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-networking#public-ipv4-per-virtual-machine

**Comment by vakkur** [comment]
@deeksha-microsoft  Thank you, I am using NAT Gateway service to have a fixed publicip.
