### ISSUE TITLE
Azure portal shows wrong backend targets in a rule

### ISSUE THREAD

**Issue by rlevchenko** [Azure/application-gateway-kubernetes-ingress#986]
**Describe the bug**

HTTP 80 sample application - backend target is being set to the right backend pool (sample app)
HTTPS, custom port and application with url path-routing - backend target/https settings in a rule are being set to defaultaddresspool **BUT!** **everything works fine!** (backends are healthy, I can open a website without any issues; logs are fine as well) BUG? (portal or..?) It's likely Azure portal issue..

### Backend target

![image](https://user-images.githubusercontent.com/47359229/91183102-bb2dbe00-e6f3-11ea-958b-b0d128ca9b53.png)

Additionally, if I go to the backend pools page I see that backend pool has 1 rule associated to. However, the rule is not shown in the "edit pool" page (but should be)

![image](https://user-images.githubusercontent.com/47359229/91184344-33e14a00-e6f5-11ea-94a1-24106e09c3b5.png)

Also, I noticed that host name is not shown. Seems like because of https://docs.microsoft.com/en-us/azure/application-gateway/multiple-site-overview#wildcard-host-names-in-listener-preview 

### Hostname

![image](https://user-images.githubusercontent.com/47359229/91183340-0647d100-e6f4-11ea-9956-789e1b2ad47b.png)

---
AGIC is the latest
AKS 1.17.9

**Comment by vishal8k** [comment]
@rlevchenko  @akshaysngupta  The hostnames not displaying in portal is a know issue discussed in #962 The hostnames issue is only with portal. You can still view them using AZ cli or powershell commands. With respect to what you have mentioned about the default address pool being displayed in the portal, that is the expected behavior for path based routes. The target associated with `/` will be displayed in the top and other path-based routes will be displayed in the bottom as shown in your screenshot. Since in your configuration there is not target associated with `/` and there are only path-based routes the defaultaddresspool is displayed as a default selection. Hence I don't see any other new bug or issue here. This shall be closed. Lemme know if there is something else you want to address regarding this.

**Comment by rlevchenko** [comment]
Looks like the new portal shows hostnames and rules correctly. I'm closing the issue.
