### ISSUE TITLE
Change the application Gateway frontend port to custom value 

### ISSUE THREAD

**Issue by amjadaljunaidi** [Azure/application-gateway-kubernetes-ingress#998]
**Is your feature request related to a problem? Please describe.**
we need to change frontend port (listners) to custom one like 8080 or 8443

**Describe the solution you'd like**
when using AGIC, the frontend ports created on 80 or 443, is there away to use custom port like 8080 or 8443

**Comment by akshaysngupta** [comment]
@amjadaljunaidi Here is the PR adding this feature: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/974
We will merge this soon and create a beta release for you to try.

**Comment by rpushpkar** [comment]
We also looking for the solution in which we can assign different IP to the port , one listener to the private and other to public but because of Application Gatewyt limitation we are not able to achieve this. As a workaround i have tried by assigning IP's to different port it worked but when i again update y ingress it clean off the previous configuration then it again remain the manual work.
